#!/usr/bin/python3

from subprocess import Popen, PIPE, STDOUT
import sys
sys.path[0] = sys.path[0][:-6]

from snippets import system, parseargs

src, dst = sys.argv[1:]

# scan the partition with blkid
# TODO: lire le résultat de sfdisk -d aussi ? pour les flags
out, err = system(f"/usr/sbin/blkid {src}")
assert err == 0
args = parseargs(out.split(": ")[1])
uuid = args["UUID"]

out, err = system(f"mkfs.ext4 -U {uuid} {dst}")
assert err == 0
print(f"created ext4 filesystem on {dst}")

print(f"copying files from {src} to {dst}. this may take a long time")

_, err = system(f"mount {src} mnt/src")
assert err == 0
_, err = system(f"mount {dst} mnt/dst")
assert err == 0

out, err = system(f"cp -a mnt/src/* mnt/dst")
assert err == 0
out, err = system("umount mnt/src mnt/dst")
assert err == 0

print(f"cloned contents of {src} to {dst}")
