#!/usr/bin/python3

from subprocess import Popen, PIPE, STDOUT
import sys


def system(cmd, stdin=None, stderr=False):
    # merge stdout and stderr, and return error code instead
    if stdin is not None:
        stdin = stdin.encode()
    process = Popen(cmd, shell=True,
                    stdout=PIPE,
                    stderr=PIPE if stderr else STDOUT)
    out, err = process.communicate(stdin)
    returncode = process.returncode
    if stderr:
        return out.decode(), err.decode(), returncode
    else:
        return out.decode(), returncode


# TODO the partition table (sfdisk -d or sgdisk --backup=) is already written in ../part_table0 and ../part_table1, but should not be needed


# the partitions can be scanned with blkid {src}

src, dst = sys.argv[1:]

# TODO: lire le résultat de sfdisk -d aussi ? pour les flags

out, err = system(f"/usr/sbin/blkid {src}")
assert err == 0
print(out)
#system("mount {src} mnt/src")
"""
    # TODO: check if the bootable flag should be set here
from subprocess import Popen, PIPE, STDOUT
system(mkfs.ext4 -U <uuid> dst)
system(mount src mnt/src)
system(mount dst mnt/dst)
system(cp -a mnt/src/* mnt/dst)
system(umount mnt/src mnt/dst
"""
