#!/usr/bin/python3
import sys

# <projectdir>/clone -> <projectdir>
sys.path[0] = sys.path[0][:-6]

from snippets import system, parseargs


src, dst = sys.argv[1:]

# scan partition with blkid
out, err = system(f"/usr/sbin/blkid {src}")
assert err == 0
_, args = out.split(": ")
args = parseargs(args)

uuid = args["UUID"]

# create the swap
out, err = system(f"mkswap -U {uuid} {dst}")
assert err == 0
print(f"created swap on {dst}")

